# Generated by Django 4.2.3 on 2023-10-22 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.AddField(
            model_name='songs',
            name='sample',
            field=models.FileField(default='settings.MEDIA_ROOT/audio/_Richard-Cocciante-Le-Coup-de-Soleil.mp3', upload_to='audio/'),
        ),
    ]
